# Generated by Django 4.0.4 on 2022-05-16 19:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                (
                    "serial_number",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("manufacturer", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name_plural": "Aircrafts",
            },
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin", models.CharField(max_length=200)),
                ("destination", models.CharField(max_length=200)),
                ("flight_number", models.CharField(max_length=4)),
                ("departure_time", models.DateTimeField()),
                ("arrival_time", models.DateTimeField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "aircraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.aircraft"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Flights",
                "ordering": ("departure_time",),
            },
        ),
    ]
