# Generated by Django 4.0.4 on 2022-05-17 18:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("manufacturer", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name_plural": "Aircrafts",
            },
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin", models.CharField(max_length=200)),
                ("destination", models.CharField(max_length=200)),
                ("flight_number", models.CharField(max_length=5)),
                (
                    "departure_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("arrival_time", models.DateTimeField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Last updated"),
                ),
                (
                    "aircraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.aircraft"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Flights",
                "ordering": ("departure_time",),
            },
        ),
    ]
