# Generated by Django 4.0.4 on 2022-05-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Last updated"),
        ),
    ]
